### ISSUE TITLE
To-do

### ISSUE THREAD

**Issue by prashantgupta24** [prashantgupta24/automatic-mouse-mover#5]
- [x] App info
- [x] Update Readme
- [x] Icon
- [x] Badges
- [x] Disable button once selected
- [x] Handle machine sleep events
- [x] Godoc
- [x] Improve tests
- [x] Incorporate latest machine sleep handler
- [x] fix Lint fail on icon.go
